### PR TITLE
Windows does not support termios, guard its use

### PR DESCRIPTION
**Pull request by dukrat**
allow to run on win32 by restricting termios to sys.platform!=win32

### CODE REVIEW

**Comment by mcrute** [comment]
Thanks for the contribution! In the current state it's not quite ready to merge because it has broken the build. Please make sure to run the `validate` target of `setup.py` before you submit a pull request to make sure that the code style and tests pass within your development environment.

[This change](https://github.com/mcrute/pydora/commit/b91a580568a50a92b1d13ea4c836afb60ef8b4df) introduced the termios behavior that's breaking  and I think the entire point was just to hide the user input during playback to prevent control characters that a user enters from displaying in the playback list, which is more of a cosmetic feature than anything else. In general I support disabling this feature to make Pydora usable for Windows users.

I'd prefer to handle this as a feature check by guarding the import and disabling `set_echo` if termios is not present on the platform as this is more robust than platform checking. Can you try the latest code from the master branch and confirm that this fixes the problem you're seeing?

**Comment by mcrute** [comment]
It also looks like there's a way to preserve the `set_echo` functionality using `ctypes` and the [SetConsoleMode](https://docs.microsoft.com/en-us/windows/console/setconsolemode) Windows API call. I'll take a stab at getting this working but I don't have a great way to test it so I'll push it to a branch if you want to give it a try.

**Comment by mcrute** [comment]
I just pushed a `windows_echo` branch that preserves the echo functionality by adding a Windows-specific driver to do what the `termios` driver does. Would you mind testing that branch and if it works I'll merge it.

**Comment by dukrat** [comment]
Alright.  Not used to the python development stuff yet.  Thanks for the tips.  

That sounds like a way better way to handle it.  

I tested the windows_echo branch.  setup.py validates it and it works fine for me.  But, I'm not using pydora directly.  I'm using it as part of https://github.com/rectalogic/mopidy-pandora  So if there's anything in particular you want me to test let me know.

**Comment by mcrute** [comment]
@dukrat I guess I just assumed you were using the command line player given the error you encountered. Since the windows_echo branch works for you I'm going to close this and merge the changes into 1.9.0 which should be released sometime later tonight or tomorrow. Thanks!

**Pull request closed without merging**
