### PR TITLE
Fix for unhandled SysCallError exceptions

### PR DESCRIPTION
**Pull request by jcass77**
Potential fix for https://github.com/mcrute/pydora/issues/28.

### CODE REVIEW

**Comment by jcass77** [comment]
I don't think this works quite as expected. I now get:

Error changing track: bad handshake: SysCallError(-1, 'Unexpected EOF')

Could be that we have to re-initiate the entire connection starting with partner login?

Also need to figure out if OpenSSL should be a package dependency - I thought it came bundled with requests but does not appear to be the case.

This PR needs more testing.

**Comment by jcass77** [comment]
Ok, it looks like decorating transport.__call__ in its entirety did the trick.

I also made the suggested code changes and added a test case. I **think** this should be fixed now.

**Comment by mcrute** [comment]
I want to do a little more testing with this before I push it into a release and I'm a little uneasy about taking a pyOpenSSL dependency.

**Comment by jcass77** [comment]
I haven't had any more connection issues in the two weeks that I've been using this, so it appears to be working surprisingly well on my setup.

The pyOpenSSL dependency is literally only there to catch the ```SysCallError``` exception, which seems like bit of an overkill. Perhaps it can be wrapped in a higher level exception and the message parsed to determine the type and error code? It's a bit of an anti-pattern but might be acceptable given the circumstances?

**Comment by mcrute** [comment]
It looks like they have an exception hierarchy that's rooted at the built-in `Exception`. It might be best to just catch that. At the transport level there's very little that's going to fail that can't be retried. Auth errors and other un-retryable conditions are handled at a higher level.

**Comment by mcrute** [comment]
Actually, this doesn't work for Python 3.4 on Mac OS X due to a missing FFI dependency. So we'll probably just have to resort to catching exception.

**Comment by jcass77** [comment]
Will do!

**Pull request merged**
