### PR TITLE
Enhancement: Adds additional audio urls

### PR DESCRIPTION
**Pull request by Skybound1**
Adds `additionalAudioUrl` for the `station.getPlaylist` method. I added the `Enum` type as an extra thing so people can see the available options via code completion.

### CODE REVIEW

**Comment by Skybound1** [comment]
Thanks @mcrute for reviewing the code. I'm a bit swamped this week, but will aim to get the changes requested done as soon as I can :)

**Comment by Skybound1** [comment]
@mcrute I have made the changes requested, please let me know what you think.

**Comment by mcrute** [comment]
LGTM. Thanks for your contribution!

**Comment by mcrute** [comment]
This has been released to PyPi as 1.13.0

**Pull request merged**
