### PR TITLE
Better HTTP support, proper padding verification

### PR DESCRIPTION
**Pull request by t-8ch**
Contains support for proxies, connectionpooling, pianobar compat, proper padding verification.

### CODE REVIEW

**Comment by mcrute** [comment]
I'm happy to merge most of this as-is pending the other minor comments. Would you be willing to split the pianobar config changes into a separate pull request? I'll merge them as well but I want to refactor out the config-parser bits from the `APIClient` into a client builder class. I'll take a pass at that on a branch with the current config parser and dictionary-based client builder methods and send you a pull-request for comment.

**Comment by t-8ch** [comment]
@mcrute done

**Comment by mcrute** [comment]
Merged. This will be in the 1.3.0 release which should be out by the end of the weekend.

**Comment by t-8ch** [comment]
Nice, you may want to add proxy support to your native configuration file.

**Comment by mcrute** [comment]
Good idea. I'm probably also going to deprecate my config support in favor of your pianobar config contributions; no reason to support competing config formats.

**Comment by t-8ch** [comment]
Hm, I would not rip out the old configuration.
People are lazy (I was too lazy to convert my pianobar config and keep it in sync).

**Pull request merged**
